version: '3.4'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: mssql
    volumes:
      - ./mssql:/var/opt/mssql/data
      - /etc/localtime:/etc/localtime
    environment:
      - "MSSQL_SA_PASSWORD=Aa123456."
      - "ACCEPT_EULA=Y"
      - "TZ=Asia/Shanghai"
    ports:
      - "1433:1433"
    networks:
      - blog

  registry.cn-shenzhen.aliyuncs.com/tokengo/blog-api:
    build:
      context: .
      dockerfile: ./src/server/Blog.HttpApi.Host/Dockerfile
    container_name: blog-api
    environment:
      - "OPENAI_API_KEY="
      - "ClientSecret="
    depends_on:
      - mssql
    networks:
      - blog

  registry.cn-shenzhen.aliyuncs.com/tokengo/blog-web:
    build:
      context: .
      dockerfile: ./src/web/Blog.Server.Web/Dockerfile
    container_name: blog-web
    networks:
      - blog

networks:
  blog:
    external: true
